server:
  port: 8081

spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: ${GIT_URI}
          searchPaths: ${GIT_CONFIG_SEARCH_PATHS}
          username: ${GIT_USERNAME}
          password: ${GIT_PASSWORD}
          default-label: main
          tryMasterBranch: true
  security:
    user:
      name: ${SECURITY_USERNAME}
      password: ${SECURITY_PASSWORD}